'crawler':
  name: 'crawler'
  address: 
   - "cluster0-shard-00-00-zlhwd.gcp.mongodb.net:27017"
   - "cluster0-shard-00-01-zlhwd.gcp.mongodb.net:27017"
   - "cluster0-shard-00-02-zlhwd.gcp.mongodb.net:27017"
  repset_name: "Cluster0-shard-0"
  dbname: "db"
  user: "admin"
  pass: "zc3wOexqh7GDzwld"
  timeout: 5
  is_ssl: true
  source: "admin"
  pool_limit: 100
  read_pref: "SecondaryPreferred"